### PR TITLE
3.0.0—Modularize all the things, GraphicsMagick is optional, (better) Windows support

### LINKED ISSUE #17: Expose original character / rgb values as generated
The values returned are perfect for consuming within a console, however for my project I needed the original character and rgb as generated.

Perhaps add a "pure data mode" boolean to the options and if so, add to an array structure instead of converting to final console string.

(Feature request)

### LINKED ISSUE #24: Passing raw file contents of an image
Any tips for passing a raw image (in memory) to `image-to-ascii`?

I'd love to pass a string or file-like object, this only accepts the raw image in pixels or a path to a file (and I'd prefer not to have to write out temp files).

### PR DESCRIPTION
**Pull request by IonicaBizau**
I have been working on this new major release since September, last year. It was a huge work to break, split and modularize the previous code. :sweat_smile: 

GraphicsMagick is still recommended to be installed on the system, but in case if it's not installed, the library will compile [`lwip`](https://github.com/EyalAr/lwip)—a nice Node.js image processor. :sparkles: 

After upgrading to [`couleurs@6.0.0`](https://github.com/IonicaBizau/node-couleurs) we got a better Windows support—in fact, this library is now compatible with the 16 colors from the Windows command prompt. Pretty cool, eh? :grin: 

I refactored the code base from scratch. I used ES2015 features which means you should run this using Node.js >= 4.0.0.

Another nice feature is that you can use an existing image buffer as input. Using an url or local path works too. :dizzy:  Fixes #24.

Few other features are the new options that I added: custom/transparent background (defaults to white), custom stringify function etc. They are documented in the README.md file. :memo: 

By turning off the `concat` and `stringify` options we will get an object back (not a string). This allows us to modify the image before stringifying it. Fixes #17.

----

## Windows Version

I split the monolithic structure that was here before in small reusable modules that are dependencies of this library. If someone is interested to see how the dependencies graph looks like, there you go:

 - [`image-to-ascii`](https://github.com/IonicaBizau/image-to-ascii)—A Node.JS module that converts images to ASCII art.
    - [`asciify-pixel-matrix`](https://github.com/IonicaBizau/asciify-pixel-matrix)—Asciifies a matrix of pixels.
       - [`asciify-pixel`](https://github.com/IonicaBizau/asciify-pixel)—Asciifies a pixel object.
          - [`couleurs`](https://github.com/IonicaBizau/node-couleurs)—Add some color and styles to your Node.JS strings.
            - [`ansy`](https://github.com/IonicaBizau/ansy)—Cross platform ANSI colors made easy.
               - [`custom-return`](https://github.com/IonicaBizau/custom-return)—Generate a function that returns a constant.
                 - [`noop6`](https://github.com/IonicaBizau/noop6)—No operation as a module using an arrow function.
           - ...
    - [`pixel-bg`](https://github.com/IonicaBizau/pixel-bg)—Change the pixel background color.
    - [`pixel-class`](https://github.com/IonicaBizau/pixel-class)—A tiny class for pixel manipulation.
    - [`pixel-white-bg`](https://github.com/IonicaBizau/pixel-white-bg)—Set white background color for a pixel.
  - [`compute-size`](https://github.com/IonicaBizau/compute-size)—Helper tool for resizing the things.
    - [`fixed-or-percent`](https://github.com/IonicaBizau/fixed-or-percent)—Get the percent or fixed value.
      - [`is-percent`](https://github.com/IonicaBizau/is-percent)—Check if a given value is in the percent format.
        - [`last-char`](https://github.com/IonicaBizau/last-char)—Get the last character in a provided string.
      - [`percent-value`](https://github.com/IonicaBizau/percent-value)—Percentage helper functions.
    - [`map-o`](https://github.com/IonicaBizau/map-o)—Array-map like function for objects.
      - [`iterate-object`](https://github.com/IonicaBizau/iterate-object)—A convenient way to iterate objects.
  - [`image-parser`](https://github.com/IonicaBizau/image-parser)—An image parser that works.
    - [`err`](https://github.com/IonicaBizau/err)—A tiny library to create custom errors in JavaScript.
      - [`typpy`](https://github.com/IonicaBizau/typpy)—A better typeof for JavaScript.
    - [`gm-tools`](https://github.com/IonicaBizau/gm-tools)—Friendly tools for interacting with GraphicsMagick.
      - ...
    - [`lwipify`](https://github.com/IonicaBizau/lwipify)—Convert images in lwip objects.
      - [`lwip2`](https://github.com/IonicaBizau/lwip2)—A friendlier wrapper around the lwip library.
        - [`gm-installed`](https://github.com/IonicaBizau/gm-installed)—Check if GraphicsMagick is installed.
          - [`prgm-installed`](https://github.com/IonicaBizau/prgm-installed)—Check if a program is available on the system.
            - ...
      - [`url-remote`](https://github.com/IonicaBizau/url-remote)—Checks if a given url is a remote url or not.
        - [`url-local`](https://github.com/IonicaBizau/url-local)—Checks if a given url is a local url or not.
          - [`parse-url`](https://github.com/IonicaBizau/parse-url)—An advanced url parser supporting git urls too.
            - [`is-ssh`](https://github.com/IonicaBizau/is-ssh)—Check if an input value is a ssh url or not.
               - [`protocols`](https://github.com/IonicaBizau/protocols)—Get the protocols of an input url.
    - [`pixel-class`](https://github.com/IonicaBizau/pixel-class)—A tiny class for pixel manipulation.
      - [`deffy`](https://github.com/IonicaBizau/deffy)—Small and fast library to set default values.
        - [`typpy`](https://github.com/IonicaBizau/typpy)—A better typeof for JavaScript.
  - [`imgpx`](https://github.com/IonicaBizau/imgpx)
    - [`lwip-pixels`](https://github.com/IonicaBizau/lwip-pixels)
      - [`pixel-class`](https://github.com/IonicaBizau/pixel-class)—A tiny class for pixel manipulation.
        - [`deffy`](https://github.com/IonicaBizau/deffy)—Small and fast library to set default values.
          - [`typpy`](https://github.com/IonicaBizau/typpy)—A better typeof for JavaScript.
    - [`lwipify`](https://github.com/IonicaBizau/lwipify)—Convert images in lwip objects.
      - ...
  - [`one-by-one`](https://github.com/IonicaBizau/one-by-one)
    - [`deffy`](https://github.com/IonicaBizau/deffy)—Small and fast library to set default values.
      - [`typpy`](https://github.com/IonicaBizau/typpy)—A better typeof for JavaScript.
      - ...
  - [`terminal-char-width`](https://github.com/IonicaBizau/terminal-char-width)
    - ...
  - [`ul`](https://github.com/IonicaBizau/node-ul)—A minimalist utility library.
    - [`deffy`](https://github.com/IonicaBizau/deffy)—Small and fast library to set default values.
    - [`typpy`](https://github.com/IonicaBizau/typpy)—A better typeof for JavaScript.

### CODE REVIEW

**Comment by rgbkrk** [comment]
> I used ES2015 features which means you should run this using Node.js >= 4.0.0.

game on for us!

love the Windows support

**Comment by IonicaBizau** [comment]
> game on for us!

What does that mean? Is it something good? :smile: 

> love the Windows support

Maybe one day Microsoft will switch from 16 colors to 16 million colors in Command Prompt. :joy:

**Comment by rgbkrk** [comment]
> What does that mean? Is it something good? :smile:

Yes! The project I'm using this in requires node 4+. The phrase "game on" in this context means that "we're good to go, let's do this."

> Maybe one day Microsoft will switch from 16 colors to 16 million colors in Command Prompt. :joy:

Is it different in PowerShell?

**Comment by IonicaBizau** [comment]
> Is it different in PowerShell?

I have no idea. Just try it. Basically it's smart enough to get the best compatibility: 16 million colors (true color), 256 colors, 16 colors, no color at all. :grin:

**Comment by rgbkrk** [comment]
Ah, k. Cool!

**Comment by yowakita** [comment]
This is awesome, I definitely wanna play around with this this weekend.

**Pull request merged**
